# Generated by Django 5.2.1 on 2025-09-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_username_alter_client_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
