# Generated by Django 5.2.1 on 2025-09-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
